### ISSUE TITLE
"File name too long" under `stablehlo/testdata/`

### ISSUE THREAD

**Issue by janpfeifer** [openxla/stablehlo#1364]
### What happened?

I'm cross-posting the issue previously reported in [tensorflow/tensorflow #60126](https://github.com/tensorflow/tensorflow/issues/60126) here, because it may be simpler to address this here.

Compilation in some systems seem to be breaking on the "file name too long".

In particular I'm trying to link OpenXLA in my own project, and I'm also bumping into this issue, when `openxla/xla` tries to pull  `stablehlo`:

```
...
INFO: repository @stablehlo' used the following cache hits instead of downloading the corresponding file.            
 * Hash '5f4f2dbba503bc18e1a64c3b87a51b8571519ca18158937e3048c094ae90e548' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/openxla/stablehlo/archive/458bdd95771e9861e6488868e315a1b0340058ba.zip                                                 
If the definition of 'repository @stablehlo' was updated, verify that the hashes were also updated.      
ERROR: An error occurred during the fetch of repository 'stablehlo':                                     
   Traceback (most recent call last):                                                                    
        File "/mnt/.cache/external/xla/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl                                                                                                        
                ctx.download_and_extract(           
Error in download_and_extract: java.io.IOException: Error extracting /mnt/.cache/external/stablehlo/temp1913717006884866717/458bdd95771e9861e6488868e315a1b0340058ba.zip to /mnt/.cache/external/stablehlo/temp1913717006884866717: /mnt/.cache/external/stablehlo/stablehlo/testdata/vmap_dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_dynamic.mlir.0_9_0.bc (File name too long)       
ERROR: /mnt/WORKSPACE:73:15: fetching _tf_http_archive rule //external:stablehlo: Traceback (most recent call last):                                                                                              
        File "/mnt/.cache/external/xla/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl                                                                                                        
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /mnt/.cache/external/stablehlo/temp1913717006884866717/458bdd95771e9861e6488868e315a1b0340058ba.zip to /mnt/.cache/external/stablehlo/temp1913717006884866717: /mnt/.cache/external/stablehlo/stablehlo/testdata/vmap_dot_general_batch_dimensions_lhs_float32_8_4_3_3_4__rhs_float32_4_8_3_4_2__dimensionnumbers____4_3___3_2_____0_1___1_0_dynamic.mlir.0_9_0.bc (File name too long)
```

I opened the zip file, after quick investigation:

```
$ ls stablehlo-458bdd95771e9861e6488868e315a1b0340058ba/stablehlo/testdata/ | while read ii ; do echo ${#ii} $ii ; done | sort -n | tail -n 3
142 vmap_select_and_gather_add_window_strides_shape_float32_4_6__selectprim_le_windowdimensions__2__2__w-7130227668472867832_dynamic.mlir.0_9_0.bc
142 vmap_select_and_scatter_add_dtypes_shape_float32_2_4_6__selectprim_ge_windowdimensions__2__2__2__win-6232315144219558965_dynamic.mlir.0_9_0.bc
142 vmap_triangular_solve_complex_transformations_a_complex64_4_4__b_complex64_4_1__leftside_True_lower_-5512541391217876637_dynamic.mlir.0_9_0.bc
```

It seems that the largest file is only 142 chars and not 255, so likely an issue with Bazel's java extractor ? But since the name seems to already be trimmed some (replace by some hash at the end?), maybe it would be easy to trim it further a bit ?

Any suggestions ?

### Version information

I'm trying to compile `openxla/xla` at commit hash `0d9a1dbc2b02a316afbae3e3c9b4083dc16b894b`.

The `openxla/stablehlo` that it tries to download is at commit hash `458bdd95771e9861e6488868e315a1b0340058ba`

**Comment by janpfeifer** [comment]
Ok, a bit more investigation, I noticed that even `git clone github.com/openxla/stablehlo` was failing. And digging further, I noticed I was using `ecryptfs` on my home directory -- otherwise an ext4. And searching I found out `ecryptfs` has a limit of 143 length on names, that probably was hit. I moved my development area to a plain ext4 and things worked again.

Still, since it already limits the length of file names, maybe it could be made even a bit shorter not to bump into ecrypfs (and others) ?

**Comment by atondwal** [comment]
@GleasonK could you take a look at shrinking the filenames in testdata a bit?
